import { defineConfig } from 'vitepress'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: "杰克-逊の黑豹",
  description: "JasonZhang's personal website",
  srcDir: "./docs",
  /**
   *  How to resolve favicon of Safari?
   * 
   *  these `link` configs follow https://favicon.io/favicon-converter/,
   *  these pictures also generated by that website:
   *   /public/apple-touch-icon.png
   *   /public/favicon-32x32.png
   *   /public/favicon-16x16.png
   *   /public/favicon.ico
   *   /public/site.webmanifest
   *   /public/android-chrome-192x192.png
   *   /public/android-chrome-512x512.png
   *  
   *  thanks to this ico generator website!
   * 
   *  in chrome browser, you can take a regular PNG file as browser favicon,
   *  but in Safari browser, it has some requirements or limits in the size of favicon,
   *  there is a related question here: https://stackoverflow.com/questions/64236057/how-to-create-a-favicon-for-safari-14
   * 
   *  I follow this question and write these codes.
   */
  head: [
    // for chrome and other browsers
    ["link", { rel: "icon", href: "/favicon.png" }],
    // only for Safari browser
    [
      'link',
      { rel: 'apple-touch-icon', sizes: "180x180", href: `/apple-touch-icon.png` }
    ],
    [
      'link',
      { rel: "icon", type: "image/png", sizes:"32x32", href: "/favicon-32x32.png" },

    ],
    [
      'link',
      { rel: "icon", type: "image/png", sizes: "16x16", href: "/favicon-16x16.png" },
    ],
    [
      'link',
      { rel: "manifest", href: "/site.webmanifest"}
    ]
  ],
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    logo: "/favicon.png",
    aside: false,
    nav: [
      { 
        text: 'Me', 
        activeMatch: `^/me/`,
        items: [
          { text: 'work experience', link: '/me/work-experience'},
          { text: 'work thoughts', link: '/me/work-thoughts'},
          { text: 'my life', link: '/me/my-life'},
        ],
      },
      { 
        text: 'Go', 
        activeMatch: '^/go/',
        items: [
          { text: 'how to learn', link: '/go/how-to-learn'},
        ],
      },
      { 
        text: 'Rust', 
        activeMatch: '^/rust/',
        items: [
          { text: 'how to learn', link: '/rust/how-to-learn'},
        ],
      },
      { text: 'Frontend', link: '/frontend'},
      { text: '开源项目', link: '/open-source'},
      { text: '博客', link: '/blog'}
    ],
    sidebar: {
      "/me": [
        {
          text: 'About Me',
          items: [
            { text: 'work experience', link: '/me/work-experience' },
            { text: 'work thoughts', link: '/me/work-thoughts' },
            { text: 'my life', link: '/me/my-life'},
          ]
        }
      ],
      "/go": [
        { text: "how to learn", link: '/go/how-to-learn'}
      ],
    },

    socialLinks: [
      { icon: 'github', link: 'https://github.com/zhangzhuang15?tab=repositories' },
    ]
  },
  base: "/"
})
